-- Project generated by script.
-- Date: Qui,15/08/2013-15:27:34
-- Author: 
-- Comments: Entity Description: inversor.
 
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_unsigned.all;
use ieee.std_logic_arith.all;
 
entity inversor is
	port (a: in std_logic; y: out std_logic);
end inversor;
 
architecture logica of inversor is
  
  
begin
  -- Commands.
  y<= not a;
end logica;

