-- Project generated by script.
-- Date: Qui,15/08/2013-15:29:15
-- Author: 
-- Comments: Entity Description: nand3.
 
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_unsigned.all;
use ieee.std_logic_arith.all;
 
entity nand3 is
	port (a, b, c: in std_logic; y: out std_logic);
end nand3;
 
architecture logica of nand3 is
  
  
begin
  -- Commands.
  y<= not(a and b and c);
end logica;

