-- Project generated by script.
-- Date: Qui,15/08/2013-15:27:14
-- Author: 
-- Comments: Entity Description: and3.
 
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_unsigned.all;
use ieee.std_logic_arith.all;
 
entity and3 is
	port (a, b, c: in std_logic; y: out std_logic);
end and3;
 
architecture logica of and3 is
  
  
begin
  -- Commands.
  y<= a and b and c;
end logica;

