-- Project generated by script.
-- Date: Qui,15/08/2013-15:25:46
-- Author:
-- Comments: Entity Description: circuito.
 
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_unsigned.all;
use ieee.std_logic_arith.all;
 
entity circuito is
	port (a, b, c, d: in std_logic; s: out std_logic);
end circuito;
 
architecture estrutural of circuito is
  -- Declaration of Components.
 component and3
 	port(a,b,c: in std_logic; y: out std_logic);
 end component;

 component inversor
 	port(a: in std_logic; y: out std_logic);
 end component;

 component nand3
 	port(a,b,c: in std_logic; y: out std_logic);
 end component;

 component nor3
 	port(a,b,c: in std_logic; y: out std_logic);
 end component;

 component or4
 	port(a,b,c,d: in std_logic; y: out std_logic);
 end component;


  -- Signals declaration.
 signal s_A1_NOR, s_I1_A2, s_I2_OR1, s_A2_OR12, s_nor_NAND, s_or1_NAND, s_or2_NAND: std_logic;

begin
  -- Commands.
  -- Component instantiation and port mapping.
 A1: and3 port map(a=>c, b=>b, c=>a, y=>s_A1_NOR);
 INV1: inversor port map(a=>c, y=>s_I1_A2);
 INV2: inversor port map(a=>a, y=>s_I2_OR1);
 A2: and3 port map(a=>d, b=>s_I1_A2, c=>b, y=>s_A2_OR12);

 NO1: nor3 port map(a=>s_A1_NOR, b=>d, c=>b, y=>s_nor_NAND);
 OR1: or4 port map(a=>c, b=>d, c=>s_I2_OR1, d=>s_A2_OR12, y=>s_or1_NAND);
 OR2: or4 port map(a=>s_A2_OR12, b=>c, c=>b, d=>a, y=>s_or2_NAND);

 NA: nand3 port map(a=>s_nor_NAND, b=>s_or1_NAND, c=>s_or2_NAND, y=>s);


end estrutural;

