-- Project generated by script.
-- Date: Qui,15/08/2013-15:27:55
-- Author: 
-- Comments: Entity Description: nor3.
 
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_unsigned.all;
use ieee.std_logic_arith.all;
 
entity nor3 is
	port (a, b, c: in std_logic; y: out std_logic);
end nor3;
 
architecture logica of nor3 is
  
  
begin
  -- Commands.
  y<= not(a or b or c);
end logica;

